
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/layout/Footer'
import NavBar from '@/components/layout/NavBar'
import { ClerkProvider } from '@clerk/nextjs/app-beta'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dine Market',
  description: 'Generated by create next app',
  content : "width = device-width"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='overflow-x-hidden'>
      <body className={`${inter.className} overflow-x-hidden`} >
        <ClerkProvider>
        <NavBar />
        {children}
        <Footer/>
        </ClerkProvider>
        </body>
    </html>
  )
}
